'use strict'

var tables = [ "tblApplicationVersion",
"tblClient",
"tblClientGroup",
"tblClientGroupClient",
"tblClientLocation",
"tblCytologyDiagnosis",
"tblCytologyOtherConditions",
"tblCytologyReportComment",
"tblCytologySAComments",
"tblCytologyScreeningImpression",
"tblFlowMarkerPanel",
"tblFlowPanel",
"tblHost",
"tblICD9Code",
"tblImmunoComment",
"tblMaterialLocation",
"tblMarkers",
"tblOrderCategory",
"tblOrderType",
"tblPanel",
"tblPanelSet",
"tblPhysician",
"tblPhysicianClient",
"tblPhysicianClientDistribution",
"tblStainGroup",
"tblStainResult",
"tblStainResultGroup",
"tblStainResultOption",
"tblStainResultOptionGroup",
"tblStainTest",
"tblStVincent",
"tblSystemRole",
"tblSystemUser",
"tblSystemUserRole",
"tblTest",
"tblTypingShortcut",
"tblUserPreference",
"tblWebServiceAccount",
"tblWebServiceAccountClient" ]

var self = module.exports = {
  tables: tables
}
